name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: python -m pip install .[build]

    - name: Build Documentation
      if: success()
      run: |
        python build.py html --lang=en > docs/index.en.html
        python build.py html --lang=ja > docs/index.ja.html
        python build.py html --lang=pl > docs/index.pl.html
        pushd docs
        ln -s index.en.html index.html
        popd

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
